[versions]
agp = "8.9.2"
kotlin = "2.2.10"
material = "1.12.0"
pdfboxAndroid = "2.0.27.0"

[libraries]
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
pdfbox-android = { module = "com.tom-roush:pdfbox-android", version.ref = "pdfboxAndroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

